import type {
  ExportPosterBlock,
  ExportPosterFontOption,
} from '@/components/interfaces/export/types'

export const EXPORT_POSTER_FONT_OPTIONS: ExportPosterFontOption[] = [
  { label: 'Impact', value: 'Impact, Haettenschweiler, "Arial Narrow Bold", sans-serif' },
  { label: 'Trebuchet', value: '"Trebuchet MS", "Segoe UI", sans-serif' },
  { label: 'Open Sans', value: '"Open Sans", "Segoe UI", sans-serif' },
  { label: 'Montserrat', value: 'Montserrat, "Trebuchet MS", sans-serif' },
  { label: 'Bebas Neue', value: '"Bebas Neue", Impact, "Arial Narrow Bold", sans-serif' },
  { label: 'Georgia', value: 'Georgia, "Times New Roman", serif' },
  { label: 'Segoe UI', value: '"Segoe UI", Tahoma, sans-serif' },
  { label: 'Times New Roman', value: '"Times New Roman", Times, serif' },
  { label: 'Verdana', value: 'Verdana, Geneva, sans-serif' },
  { label: 'Courier New', value: '"Courier New", monospace' },
]

export function createDefaultPosterBlocks(baseTitle: string): ExportPosterBlock[] {
  return [
    {
      id: 'title',
      label: 'Titre',
      text: baseTitle || 'Grand Prix AMV',
      xPct: 6,
      yPct: 7,
      widthPct: 88,
      fontFamily: EXPORT_POSTER_FONT_OPTIONS[0].value,
      fontSize: 62,
      fontWeight: 800,
      color: '#ffffff',
      shadowColor: '#000000',
      align: 'left',
      shadowStyle: 'strong',
      visible: true,
    },
    {
      id: 'subtitle',
      label: 'Sous-titre',
      text: 'Résultats officiels',
      xPct: 6,
      yPct: 19,
      widthPct: 84,
      fontFamily: EXPORT_POSTER_FONT_OPTIONS[1].value,
      fontSize: 24,
      fontWeight: 600,
      color: '#e2e8f0',
      shadowColor: '#000000',
      align: 'left',
      shadowStyle: 'soft',
      visible: true,
    },
    {
      id: 'top',
      label: 'Bloc TOP',
      text: '1. ...\n2. ...\n3. ...',
      xPct: 6,
      yPct: 36,
      widthPct: 45,
      fontFamily: EXPORT_POSTER_FONT_OPTIONS[1].value,
      fontSize: 32,
      fontWeight: 700,
      color: '#f8fafc',
      shadowColor: '#000000',
      align: 'left',
      shadowStyle: 'strong',
      visible: true,
    },
    {
      id: 'footer',
      label: 'Pied de page',
      text: 'Merci à tous les participants',
      xPct: 6,
      yPct: 90,
      widthPct: 88,
      fontFamily: EXPORT_POSTER_FONT_OPTIONS[3].value,
      fontSize: 18,
      fontWeight: 500,
      color: '#cbd5e1',
      shadowColor: '#000000',
      align: 'left',
      shadowStyle: 'soft',
      visible: true,
    },
  ]
}
